config/routes.rb
Rails.application.routes.draw do
  devise_for :users, components: {registrations: 'registrations', sessions: 'sessions'}
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get "/homes", to: "homes#index"
  root "homes#index"
  
  get "/homes/network", to: "homes#network"
  get "/homes/group", to: "homes#group"
  get "/homes/bubble", to: "homes#bubble"
  get "/homes/map", to: "homes#map"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:registerable,
         :authentication_keys => [:username]

  ## Database authenticatable
  field :firstname, type: String
  validates :firstname,presence:true

  field :lastname, type: String
  validates :lastname,presence:true

  field :username, type: String
  validates :username,presence:true

  field :email, type: String
  field :encrypted_password, type: String
  
  
  

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time
  def will_save_change_to_email?
    false
  end

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  include Mongoid::Timestamps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    

    protected
  
    def configure_permitted_parameters
      attributes = [:firstname, :lastname, :username, :email, :password]
      devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
      
      
    end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end
    def network
    end
    def group
    end
    def bubble
    end
    def map
    end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_footer.html.haml
.footer 
  %i.fa.fa-copyright
    Copyright Elixsys 2021 to 2022
:css
  .footer{
    background-color:white;
    opacity:0.8;
    margin-top:10px;
    height:60px;
    
    display:flex;
    justify-content:center;
    align-items:center;
  }

app/views/homes/_header.html.haml
%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
.head
%nav.navbar.navbar-expand-lg.bg-light
  .container-fluid
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    %a.navbar-brand{:href => "#"}
      = image_tag("logo.png")
      -# %img{:src => "app/assets/images/logo.png",:alt => "logo"}
    #navbarSupportedContent.collapse.navbar-collapse.justify-content-center
      %ul.navbar-nav.mb-2.mb-lg-0.headerr
        - if user_signed_in?
          %li.nav-item.hm
          = link_to raw('<i class="fa fa-home" aria-hidden="true"></i>'),homes_path
          %li.nav-item.dropdown.mn
            = link_to "My Network",homes_network_path
            %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %ul.dropdown-menu
              %li
                %a.dropdown-item{:href => "#"} Network Requests
              %li
                %a.dropdown-item{:href => "#"} Network Forums
              %li
                %a.dropdown-item{:href => "#"} User Conversations
              %li
                %a.dropdown-item{:href => "#"} Message Board
              %li
                %a.dropdown-item{:href => "#"} My forum events
          %li.nav-item.dropdown.gv
            = link_to "Group View",homes_group_path
            %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %ul.dropdown-menu
              %li
                %a.dropdown-item{:href => "#"} My Groups
              %li
                %a.dropdown-item{:href => "#"} My Tasks
              %li
                %a.dropdown-item{:href => "#"} Group Milestones
              %li
                %a.dropdown-item{:href => "#"} My Events
              %li
                %a.dropdown-item{:href => "#"} Message Board
              %li
                %a.dropdown-item{:href => "#"} Group Requests
          %li.nav-item.dropdown.bv
            = link_to "Bubble View",homes_bubble_path
            %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %ul.dropdown-menu
              %li
                %a.dropdown-item{:href => "#"} Collaboration Requests
              %li
                %a.dropdown-item{:href => "#"} Conversations
          %li.nav-item.dropdown.mv
            = link_to " Map View",homes_map_path
            %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %ul.dropdown-menu
              %li
                %a.dropdown-item{:href => "#"} Collaboration Requests
              %li
                %a.dropdown-item{:href => "#"} Conversations
              %li
                %a.dropdown-item{:href => "#"} My Stats
              %li
                %a.dropdown-item{:href => "#"} Questionnaires
              %li
                %a.dropdown-item{:href => "#"}Join Groups
          %li.nav-item.so
            = link_to 'Sign Out',destroy_user_session_path ,method: :delete
        - else
          %li.nav-item.r
            = link_to 'Register',new_user_registration_path
          %li.nav-item.ol
            = link_to 'Oncology Login',new_user_session_path
%body

:css
  .mn{
     display:flex;
     padding:8px;
     align-items: center;
     justify-content: center;
  }
  nav{
    color:rgba(0,0,0,0.2);
     
  }
  .headerr {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  
  .gv{
     display:flex;
      padding:8px;
      align-items: center;
      justify-content: center;
  }
  .bv{
     display:flex;
      padding:8px;
      align-items: center;
      justify-content: center;
  }
  .mv{
     display:flex;
      padding:8px;
      align-items: center;
      justify-content: center;
  }
  .r,.ol,.so,.hm{
    padding:8px;
  }
  .mv a{
    text-decoration: none;
  }
  .bv a{
    text-decoration: none;
  }
  .gv a{
    text-decoration: none;
  }
  .mn a{
    text-decoration: none;
  }
  .ol a{
    text-decoration: none;
  }
  .r a{
    text-decoration: none;
  }
  .so a{
    text-decoration: none;
  }
  
  
  

app/views/homes/bubble.html.haml
%h1 Bubble View

app/views/homes/group.html.haml
%strong Group View

app/views/homes/index.html.haml
%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
%body
  %div{:class => 'container'}
    .views
      .row 
        .col-md-8.col-sm-6 
        .col-md-2.col-sm-3.col-xs-6.s1
          %a{:href => homes_network_path}
            .mni
              %strong My Network
          %a{:href => homes_bubble_path}
            .bvi
              %strong Bubble View
        .col-md-2.col-sm-3.col-xs-6.s2 
          %a{:href => homes_group_path}
            .gvi
              %strong Group View
          %a{:href => homes_map_path}
            .mvi
              %strong Map View
  %div{:class => 'container-fullwidth w-100 p-0 m-0'}
    .div1
      .row 
        .col-md-3.col-sm-3
          .mmp 
            %strong My Profile 
            .myprof 
              .row 
                .col-md-5.col-sm-5 
                  = image_tag("p1.jfif",style:'border-radius:50%;height:100px;width:100px;text-align:left;')
                .col-md-7.col-sm-7 
                  %strong IT Intern 
                  %br
                  %strong Cancer Research Institute 
          %a{:href => "#"}More
        .col-md-3.col-sm-3
          .mmg 
            %strong My Groups
            .groupimg
              = image_tag("gl.png",style: 'height:50px; width:50px;')
              %a{:href => "#"} IT intern 
              %br
              = image_tag("gl.png",style: 'height:50px; width:50px;')
              %a{:href => "#"} Interns
              %br
              = image_tag("gl.png",style: 'height:50px; width:50px;')
              %a{:href => "#"} IT
              %br
              = image_tag("gl.png",style: 'height:50px; width:50px;')
              %a{:href => "#"} VCR
              %br
              = image_tag("gl.png",style: 'height:50px; width:50px;')
              %a{:href => "#"} VCR Park
          %a{:href => "#"}More
              

        .col-md-3.col-sm-3
          .mmn 
            %strong My Network
            .mynet 
              =image_tag('p2.jpg',style:"height:50px;width:50px;border-radius:50%;")
              .toast.show
                .toast-head  
                  %button{"aria-label" => "Close", "data-bs-dismiss" => "toast", type: "button",:class => 'btn-close'}
                .toast-body
                  .toast-b 
                    =image_tag('p2.jpg',style: 'height:30px;width:30px;')
                    %strong Name 
                  .toast-b1 
                    %strong Intern at VCR 
                    %br
                    %i.fa.fa-tag
                    %strong Customer
                    %hr
          %a{:href => "#"}More
            
        .col-md-3.col-sm-3
          .mmf 
            %strong My Forum
            .list
              %ul
                %li VCR intern
                %li Internship
                %li Forum
                %li Research
          %a{:href => "#"}More
  %div{:class => 'container-fullwidth w-100 p-0 m-0'}
    .div2 
      .row 
        .col-md-3.col-sm-3
          %a{:href => homes_bubble_path}
            .users 
              %i.fa.fa-users
              %h4 Users 
              %p 269
        .col-md-3.col-sm-3
          %a{:href => homes_bubble_path}
            .org 
              %i.fa.fa-building-o
              %h4 Organizations 
              %p 3124
        .col-md-3.col-sm-3 
          %a{:href => homes_bubble_path}
            .groups 
              %i.fa.fa-object-group
              %h4 Groups 
              %p 343
        .col-md-3.col-sm-3
          %a{:href => homes_bubble_path}
            .forums 
              %i.fa.fa-forumbee
              %h4 Forums
              %p 110
      
    
:css
   @media only screen and (min-width: 992px) {
    .mni,.gvi,.bvi,.mvi{
      height:180px;
      width:auto;
    }
  }
  @media only screen and (max-width: 850px) {
    .mni,.gvi,.bvi,.mvi{
      height:180px;
      width:auto;
    }
  }
  @media only screen and (min-width: 992px) {
    .mmp,.mmg,.mmn,.mmf{
      height:200px;
      width:auto;
    }
  }
  @media only screen and (max-width: 850px) {
    .mmp,.mmg,.mmn,.mmf{
      height:200px;
      width:auto;
    }
  }
  @media only screen and (min-width: 992px) {
    .users,.org,.groups,.forums{
      height:90%;
      width:80%;
    }
  }
   @media only screen and (max-width: 850px) {
    .users,.org,.groups,.forums{
      height:90%;
      width:80%;
    }
  }
  *{
    box-sizing: border-box;
  }
  body{
     background-image: url('/assets/bg.jpg');
     
  }
  
  .col{
    text-align:center;
  }
  .toast{
    visibility:hidden;
    background:linear-gradient(-45deg, rgb(147, 39, 143), rgb(71, 114, 226));
    width:70%;
    border-radius:0%;
    
  }
  .toast-head{
    text-align:right;
  }
  .toast-b{
    background:white;
    width:100%;
    padding:2px;

  }
  .toast hr{
    color:white;
    border:2px solid white;
    opacity:1;
  }
  .toast-b1{
    padding:6px;
  }
  .toast-body{
    padding:6px;
    text-align:left;
  }
  .mynet:hover .toast{
    visibility:visible;
    
    position:relative;
    left:20px;
    
  }
  
  .mmg{
    width:100%;
  }
  .groupimg{
    overflow-y:auto; 
    height: calc(100% - 40px);
    text-align:left;
  }
  .list{
    text-align:left;
   
  }
  .myprof {
    padding-top:30px;
    
  }
 
     
  .mni,.gvi,.bvi,.mvi{
    
    color: white;
    padding:2px;
    margin:10px 1px;
    text-align:center;
    box-shadow: 2px 2px 1px rgb(255,250,250);
    display:flex;
    align-items:center;
    justify-content:center;
    opacity: 0.7;
  }
  .mni,.gvi,.bvi,.mvi {
    opacity:1;
  }
  
  .mni{
    background-image: url('/assets/mn.png');
    
  }
  .gvi{
    background-image: url('/assets/gv.png');
    
  }
  .bvi{
    background-image: url('/assets/bv.png');
    
  }
  .mvi{
    background-image: url('/assets/mv.png');
    
  }
  .s1,.s2{
    display:flex;
    flex-direction:column;
  }
  .row a{
    text-decoration:none;
  }
  .row{
    margin:2px;
    text-align:center;
  }
  .views{
    margin-top:20px;
    margin-bottom:100px;
    
  }
  .div1{
    background: white;
    border-radius:2px;
    margin-left:25px;
    margin-right:25px;
    padding:5px 2px;
    opacity:0.9;
    
  }
  .mmp,.mmg,.mmn,.mmf{
    border: 1px  solid black;
    border-radius:3px;
    padding:3px 2px;
  }
  .mmp, .mmg, .mmn, .mmf {
    text-align:center;
  }
  .div2{
    background:white;
    padding:5px;
    padding-top:20px;
    
    opacity:0.8;
    
    border-radius:5px;
    margin-left:25px;
    margin-right:25px;
    margin-top:15px;
  }
  .users,.org,.groups,.forums{
    color:white;
    border-radius:15%;
    background:linear-gradient(-45deg, rgb(147, 39, 143), rgb(71, 114, 226));
    padding:5px;
  }
  .users .fa{
    font-size:50px;
  }
  .org .fa{
    font-size:50px;
  }
  .groups .fa{
    font-size:50px;
  }
  .forums .fa{
    font-size:50px;
  }

app/views/homes/main.html.haml
.container-fluid
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    %a.navbar-brand{:href => "#"}
      %img{:src => "logo.png",:alt => "logo"}
    #navbarSupportedContent.collapse.navbar-collapse.justify-content-center
      %ul.navbar-nav.mb-2.mb-lg-0
        %li.nav-item.hm
          = link_to 'Home',homes_path
        %li.nav-item.dropdown.au
          = link_to "About Us",homes_network_path
          %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
          %ul.dropdown-menu
            %li
              %a.dropdown-item{:href => "#"} Team
            %li
              %a.dropdown-item{:href => "#"} Vision
           
        %li.nav-item.dropdown.lm
          = link_to "Learn More",homes_group_path
          %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
          %ul.dropdown-menu
            %li
              %a.dropdown-item{:href => "#"} Whitepaper
            %li
              %a.dropdown-item{:href => "#"} Articles
            %li
              %a.dropdown-item{:href => "#"} Use Case Studies
            %li
              %a.dropdown-item{:href => "#"} Blog
            %li
              %a.dropdown-item{:href => "#"}Showcase
            %li
              %a.dropdown-item{:href => "#"} Announcements
             %li
              %a.dropdown-item{:href => "#"} Events
        %li.nav-item.dropdown.cu
          = link_to " Contact Us",homes_map_path
          %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
          %ul.dropdown-menu
            %li
              %a.dropdown-item{:href => "#"} Carrers
        %li.nav-item.hm
          = link_to 'Home',homes_path
            

app/views/homes/map.html.haml
%h1 Map View

app/views/homes/network.html.haml
%h1 Network

app/views/layouts/_alert.html.haml
.alert.alert-warning.alert-dismissible.fade.show{:role => "alert"}
  = notice
  %button.btn-close{"aria-label" => "close", "data-bs-dismiss" => "alert", :type => "button"}

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Platform
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css", :integrity => "sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi", :rel => "stylesheet"}/
  %body
    = render "homes/header",status: :unprocessable_entity
    - if notice
      = render "layouts/alert"
    = yield
    = render "homes/footer"
  %script{:crossorigin => "anonymous", :integrity => "sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3", :src => "https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"}